<?php

namespace ApiBundle\Entity\Repository;

/**
 * UserRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepo extends \Doctrine\ORM\EntityRepository
{
}
